FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y && apt install -y \
    apt-utils \
    clinfo \
    curl \
    build-essential \
    dkms \
    ;

RUN mkdir -p /tmp/opencl-driver-amd
WORKDIR /tmp/opencl-driver-amd

ARG AMD_DRIVER=amdgpu-pro-20.40-1147287-ubuntu-18.04
ARG FILE_EXT=.tar.xz
ARG AMD_DRIVER_URL=https://drivers.amd.com/drivers/linux

RUN curl --referer $AMD_DRIVER_URL -O $AMD_DRIVER_URL/$AMD_DRIVER$FILE_EXT

RUN dpkg --add-architecture i386
RUN apt update -y
RUN apt install -y libc6:i386 libstdc++6:i386


RUN	tar -Jxvf $AMD_DRIVER$FILE_EXT
RUN apt install -y mesa-opencl-icd
RUN	./$AMD_DRIVER/amdgpu-install -y --headless --opencl=pal,legacy 


WORKDIR /
ADD https://github.com/NebuTech/NBMiner/releases/download/v40.1/NBMiner_40.1_Linux.tgz .

RUN tar zxvf NBMiner_40.1_Linux.tgz

COPY ./entrypoint.sh .
ENTRYPOINT ["/entrypoint.sh"]
CMD ["default"]
