FROM nvidia/cuda:10.2-base-ubuntu18.04

WORKDIR = /srv/

RUN apt update && apt upgrade -y
RUN apt autoremove


WORKDIR ~/
COPY ./run.sh .
ADD https://github.com/NebuTech/NBMiner/releases/download/v36.1/NBMiner_36.1_Linux.tgz .

RUN tar zxvf NBMiner_36.1_Linux.tgz

ENV GPU_PLATFORM=1

CMD ["run.sh"]
ENTRYPOINT ["/bin/bash"]
